### ISSUE TITLE
".help" commands give error 

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/mod-queue-list-cache#9]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

![image](https://github.com/chromiecraft/chromiecraft/assets/44067875/28646a59-59e6-427c-b7e4-1903a26dd048)

### Expected Blizzlike Behaviour

Not sure if its a bug, but help text would be useful

### Source

Note: .queue is not listed in the stock AC commands list;
https://www.azerothcore.org/wiki/gm-commands

### Steps to reproduce the problem

.help queue show arena rated
.help queue show bg
.help queue show arena normal

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/6805
https://github.com/chromiecraft/chromiecraft/issues/6804
https://github.com/chromiecraft/chromiecraft/issues/6806

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by pangolp** [comment]
![WoWScrnShot_031124_144733](https://github.com/azerothcore/mod-queue-list-cache/assets/2810187/5db6273d-d52c-42f2-9dda-eb931a25f34a)

```sql
DELETE FROM `command` WHERE `name` IN ('queue show arena rated', 'queue show bg', 'queue show arena normal');
INSERT INTO `command` (`name`, `security`, `help`) VALUES
('queue show arena rated', 0, 'help for .queue show arena rated command'),
('queue show bg', 0, 'help for .queue show bg command'),
('queue show arena normal', 0, 'help for .queue show arena normal command');
```

I confirm my theory, so I just need to know what text to add.
